set noeb vb t_vb=
syntax enable
"set textwidth=75
set tabstop=8
set softtabstop=8
set shiftwidth=8
set autoindent
set cindent
set nu
set ai
set ruler
se hlsearch
"let Tlist_Auto_open=1
let Tlist_Exit_OnlyWindow=1
set cscopequickfix=s-,c-,d-,i-,t-,e-

if has("cscope")
set csprg=/opt/homebrew/bin/cscope
set csto=1
set cst
set nocsverb
" add any database in current directory
if filereadable("cscope.out")
cs add cscope.out
endif
set csverb
endif

set formatoptions=croql

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
