#! /bin/sh
# Script to bring a network (tap) device for qemu up.
# The idea is to add the tap device to the same bridge
# as we have default routing to.

# in order to be able to find brctl

br="virbr0"

ifconfig $1 up
brctl addif $br "$1"

exit
